name: Deploy and test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

  repository_dispatch:
    types: [utPLSQL-build]

jobs:
  build:

    env:
      UTPLSQL_VERSION: v3.1.13

    runs-on: ubuntu-latest

    services:
      oracle:
        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-free:23-slim
        # Provide passwords and other environment variables to container
        env:
          # DB_IMAGE: gvenzl/oracle-xe:21-slim
          # ORACLE_RANDOM_PASSWORD: true
          # DB_IMAGE: gvenzl/oracle-xe:21-slim
          ORACLE_PASSWORD: oracle
          APP_USER: my_user
          APP_USER_PASSWORD: password_i_should_change
        # Forward Oracle port
        ports:
          - 1521:1521
        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install utPLSQL ${UTPLSQL_VERSION}
        run: echo Installing ${UTPLSQL_VERSION} && sh ${{ github.workspace }}/scripts/1_install_utplsql.sh

      - name: Install utPLSQL-cli
        run: curl -Lk -o utPLSQL-cli.zip "https://github.com/utPLSQL/utPLSQL-cli/releases/download/3.1.9/utPLSQL-cli.zip" && unzip utPLSQL-cli.zip && chmod -R u+x utPLSQL-cli

      - name: Install demo project
        run: sh ${{ github.workspace }}/scripts/2_install_demo_project.sh

      - name: Install unit tests
        run: sh ${{ github.workspace }}/scripts/3_install_tests.sh

      - name: Run unit tests
        run: sh ${{ github.workspace }}/scripts/4_run_tests.sh

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


